version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: template1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"

  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
       DATABASE_URL: "postgresql://postgres:your_password@db:5432/template1"

volumes:
  postgres_data: